import type {
  MaintenanceRecord,
  Part,
  Reminder,
  ServiceType,
  StockMovement,
  Vehicle,
} from "../api/types";

export interface DemoDevice {
  id: number;
  name: string;
  uniqueId: string;
  status: string;
}

export interface DemoState {
  serviceTypes: ServiceType[];
  vehicles: Vehicle[];
  unregisteredDevices: DemoDevice[];
  records: MaintenanceRecord[];
  parts: Omit<Part, "current_stock" | "low_stock">[];
  movements: StockMovement[];
  reminders: Reminder[];
  nextIds: {
    vehicle: number;
    record: number;
    part: number;
    movement: number;
    reminder: number;
    serviceType: number;
    recordChange: number;
  };
}

const NOW = "2026-07-10T12:00:00.000Z";

export function createInitialDemoState(): DemoState {
  const serviceTypes: ServiceType[] = [
    {
      id: 1,
      name: "Oil change",
      traccar_maintenance_type: "oil-change",
      display_name: "Oil change",
      default_interval_km: 15000,
      default_interval_days: 365,
    },
    {
      id: 2,
      name: "Tire rotation",
      traccar_maintenance_type: "tire-rotation",
      display_name: "Tire rotation",
      default_interval_km: 10000,
      default_interval_days: null,
    },
    {
      id: 3,
      name: "Annual inspection",
      traccar_maintenance_type: "inspection",
      display_name: "Annual inspection",
      default_interval_km: null,
      default_interval_days: 365,
    },
    {
      id: 4,
      name: "Brake service",
      traccar_maintenance_type: null,
      display_name: "Brake service",
      default_interval_km: 40000,
      default_interval_days: null,
    },
    {
      id: 5,
      name: "Engine service",
      traccar_maintenance_type: "engine-service",
      display_name: "Engine service",
      default_interval_km: 30000,
      default_interval_days: 730,
    },
  ];

  const vehicles: Vehicle[] = [
    {
      registered: true,
      traccar_device_id: 101,
      device_name: "Truck Alpha",
      device_unique_id: "IMEI-101",
      device_status: "online",
      id: 1,
      plate: "AB-123",
      vin: "VIN0000000001",
      make: "Volvo",
      model: "FH16",
      year: 2021,
      odometer_km_cached: "187420.5",
      odometer_synced_at: NOW,
      engine_hours_cached: "4520.0",
      notes: "Primary long-haul unit",
      archived: false,
      last_service_date: "2026-06-15",
      reminder_status: "due_soon",
    },
    {
      registered: true,
      traccar_device_id: 102,
      device_name: "Van Beta",
      device_unique_id: "IMEI-102",
      device_status: "online",
      id: 2,
      plate: "CD-456",
      vin: "VIN0000000002",
      make: "Mercedes",
      model: "Sprinter",
      year: 2020,
      odometer_km_cached: "98450.0",
      odometer_synced_at: NOW,
      engine_hours_cached: "2100.5",
      notes: null,
      archived: false,
      last_service_date: "2026-05-20",
      reminder_status: "ok",
    },
    {
      registered: true,
      traccar_device_id: 103,
      device_name: "Pickup Gamma",
      device_unique_id: "IMEI-103",
      device_status: "offline",
      id: 3,
      plate: "EF-789",
      vin: null,
      make: "Toyota",
      model: "Hilux",
      year: 2019,
      odometer_km_cached: "142300.0",
      odometer_synced_at: "2026-07-01T08:00:00.000Z",
      engine_hours_cached: null,
      notes: "Site vehicle",
      archived: false,
      last_service_date: "2026-03-10",
      reminder_status: "overdue",
    },
    {
      registered: true,
      traccar_device_id: 104,
      device_name: "Bus Delta",
      device_unique_id: "IMEI-104",
      device_status: "online",
      id: 4,
      plate: "GH-012",
      vin: "VIN0000000004",
      make: "MAN",
      model: "Lion's City",
      year: 2018,
      odometer_km_cached: "312800.0",
      odometer_synced_at: NOW,
      engine_hours_cached: "8900.0",
      notes: "Passenger route #3",
      archived: false,
      last_service_date: "2026-07-05",
      reminder_status: "ok",
    },
  ];

  const unregisteredDevices: DemoDevice[] = [
    {
      id: 105,
      name: "Delivery Van 5",
      uniqueId: "IMEI-105",
      status: "online",
    },
  ];

  const records: MaintenanceRecord[] = [
    {
      id: 1,
      vehicle_id: 1,
      service_type_id: 1,
      service_type_name: "Oil change",
      performed_at: "2026-06-15",
      odometer_km: "185200.0",
      cost: "45000",
      currency: "ISK",
      performed_by: "Nordic Workshop",
      notes: "Full synthetic 15W-40",
      created_by_traccar_user_id: 1,
      created_at: "2026-06-15T14:00:00.000Z",
      parts: [{ part_id: 1, part_name: "Engine oil 15W-40", quantity: "12" }],
    },
    {
      id: 2,
      vehicle_id: 1,
      service_type_id: 2,
      service_type_name: "Tire rotation",
      performed_at: "2026-04-10",
      odometer_km: "178000.0",
      cost: "12000",
      currency: "ISK",
      performed_by: "Nordic Workshop",
      notes: null,
      created_by_traccar_user_id: 1,
      created_at: "2026-04-10T10:00:00.000Z",
      parts: [],
    },
    {
      id: 3,
      vehicle_id: 2,
      service_type_id: 1,
      service_type_name: "Oil change",
      performed_at: "2026-05-20",
      odometer_km: "96000.0",
      cost: "28000",
      currency: "ISK",
      performed_by: "City Motors",
      notes: null,
      created_by_traccar_user_id: 1,
      created_at: "2026-05-20T11:00:00.000Z",
      parts: [{ part_id: 1, part_name: "Engine oil 15W-40", quantity: "6" }],
    },
    {
      id: 4,
      vehicle_id: 3,
      service_type_id: 3,
      service_type_name: "Annual inspection",
      performed_at: "2026-03-10",
      odometer_km: "138500.0",
      cost: "18500",
      currency: "ISK",
      performed_by: "MOT Center",
      notes: "Passed",
      created_by_traccar_user_id: 1,
      created_at: "2026-03-10T09:00:00.000Z",
      parts: [],
    },
    {
      id: 5,
      vehicle_id: 4,
      service_type_id: 5,
      service_type_name: "Engine service",
      performed_at: "2026-07-05",
      odometer_km: "310500.0",
      cost: "125000",
      currency: "ISK",
      performed_by: "MAN Service",
      notes: "Major service",
      created_by_traccar_user_id: 1,
      created_at: "2026-07-05T16:00:00.000Z",
      parts: [
        { part_id: 2, part_name: "Air filter", quantity: "2" },
        { part_id: 3, part_name: "Fuel filter", quantity: "1" },
      ],
    },
    {
      id: 6,
      vehicle_id: 2,
      service_type_id: 4,
      service_type_name: "Brake service",
      performed_at: "2026-02-14",
      odometer_km: "89000.0",
      cost: "52000",
      currency: "ISK",
      performed_by: "City Motors",
      notes: "Front pads replaced",
      created_by_traccar_user_id: 1,
      created_at: "2026-02-14T13:00:00.000Z",
      parts: [{ part_id: 4, part_name: "Brake pads (front)", quantity: "1" }],
    },
    {
      id: 7,
      vehicle_id: 1,
      service_type_id: 4,
      service_type_name: "Brake service",
      performed_at: "2026-01-08",
      odometer_km: "170500.0",
      cost: "68000",
      currency: "ISK",
      performed_by: "Nordic Workshop",
      notes: null,
      created_by_traccar_user_id: 1,
      created_at: "2026-01-08T10:00:00.000Z",
      parts: [{ part_id: 4, part_name: "Brake pads (front)", quantity: "2" }],
    },
    {
      id: 8,
      vehicle_id: 4,
      service_type_id: 1,
      service_type_name: "Oil change",
      performed_at: "2026-06-01",
      odometer_km: "305000.0",
      cost: "55000",
      currency: "ISK",
      performed_by: "MAN Service",
      notes: null,
      created_by_traccar_user_id: 1,
      created_at: "2026-06-01T12:00:00.000Z",
      parts: [{ part_id: 1, part_name: "Engine oil 15W-40", quantity: "18" }],
    },
  ];

  const parts: Omit<Part, "current_stock" | "low_stock">[] = [
    {
      id: 1,
      sku: "OIL-15W40",
      name: "Engine oil 15W-40",
      unit: "L",
      min_stock: "20",
      unit_cost: "850",
      archived: false,
      created_at: "2026-01-01T00:00:00.000Z",
    },
    {
      id: 2,
      sku: "FLT-AIR",
      name: "Air filter",
      unit: "pcs",
      min_stock: "4",
      unit_cost: "3200",
      archived: false,
      created_at: "2026-01-01T00:00:00.000Z",
    },
    {
      id: 3,
      sku: "FLT-FUEL",
      name: "Fuel filter",
      unit: "pcs",
      min_stock: "3",
      unit_cost: "4500",
      archived: false,
      created_at: "2026-01-01T00:00:00.000Z",
    },
    {
      id: 4,
      sku: "BRK-PAD-F",
      name: "Brake pads (front)",
      unit: "set",
      min_stock: "2",
      unit_cost: "12500",
      archived: false,
      created_at: "2026-01-01T00:00:00.000Z",
    },
    {
      id: 5,
      sku: "WIPER-24",
      name: "Wiper blade 24\"",
      unit: "pcs",
      min_stock: "6",
      unit_cost: "1800",
      archived: false,
      created_at: "2026-01-02T00:00:00.000Z",
    },
    {
      id: 6,
      sku: "COOL-50",
      name: "Coolant concentrate",
      unit: "L",
      min_stock: "10",
      unit_cost: "1200",
      archived: false,
      created_at: "2026-01-02T00:00:00.000Z",
    },
  ];

  const movements: StockMovement[] = [
    {
      id: 1,
      part_id: 1,
      quantity: "100",
      reason: "purchase",
      maintenance_record_id: null,
      note: "Initial stock",
      created_by_traccar_user_id: 1,
      created_at: "2026-01-05T00:00:00.000Z",
    },
    {
      id: 2,
      part_id: 2,
      quantity: "10",
      reason: "purchase",
      maintenance_record_id: null,
      note: "Initial stock",
      created_by_traccar_user_id: 1,
      created_at: "2026-01-05T00:00:00.000Z",
    },
    {
      id: 3,
      part_id: 3,
      quantity: "8",
      reason: "purchase",
      maintenance_record_id: null,
      note: "Initial stock",
      created_by_traccar_user_id: 1,
      created_at: "2026-01-05T00:00:00.000Z",
    },
    {
      id: 4,
      part_id: 4,
      quantity: "6",
      reason: "purchase",
      maintenance_record_id: null,
      note: "Initial stock",
      created_by_traccar_user_id: 1,
      created_at: "2026-01-05T00:00:00.000Z",
    },
    {
      id: 5,
      part_id: 5,
      quantity: "4",
      reason: "purchase",
      maintenance_record_id: null,
      note: "Low stock demo",
      created_by_traccar_user_id: 1,
      created_at: "2026-01-05T00:00:00.000Z",
    },
    {
      id: 6,
      part_id: 6,
      quantity: "8",
      reason: "purchase",
      maintenance_record_id: null,
      note: "Low stock demo",
      created_by_traccar_user_id: 1,
      created_at: "2026-01-05T00:00:00.000Z",
    },
    {
      id: 7,
      part_id: 1,
      quantity: "-12",
      reason: "used_in_service",
      maintenance_record_id: 1,
      note: null,
      created_by_traccar_user_id: 1,
      created_at: "2026-06-15T14:00:00.000Z",
    },
    {
      id: 8,
      part_id: 1,
      quantity: "-6",
      reason: "used_in_service",
      maintenance_record_id: 3,
      note: null,
      created_by_traccar_user_id: 1,
      created_at: "2026-05-20T11:00:00.000Z",
    },
    {
      id: 9,
      part_id: 2,
      quantity: "-2",
      reason: "used_in_service",
      maintenance_record_id: 5,
      note: null,
      created_by_traccar_user_id: 1,
      created_at: "2026-07-05T16:00:00.000Z",
    },
    {
      id: 10,
      part_id: 3,
      quantity: "-1",
      reason: "used_in_service",
      maintenance_record_id: 5,
      note: null,
      created_by_traccar_user_id: 1,
      created_at: "2026-07-05T16:00:00.000Z",
    },
    {
      id: 11,
      part_id: 4,
      quantity: "-1",
      reason: "used_in_service",
      maintenance_record_id: 6,
      note: null,
      created_by_traccar_user_id: 1,
      created_at: "2026-02-14T13:00:00.000Z",
    },
    {
      id: 12,
      part_id: 4,
      quantity: "-2",
      reason: "used_in_service",
      maintenance_record_id: 7,
      note: null,
      created_by_traccar_user_id: 1,
      created_at: "2026-01-08T10:00:00.000Z",
    },
    {
      id: 13,
      part_id: 1,
      quantity: "-18",
      reason: "used_in_service",
      maintenance_record_id: 8,
      note: null,
      created_by_traccar_user_id: 1,
      created_at: "2026-06-01T12:00:00.000Z",
    },
  ];

  const reminders: Reminder[] = [
    {
      id: 1,
      vehicle_id: 1,
      service_type_id: 1,
      service_type_name: "Oil change",
      traccar_maintenance_id: 1001,
      traccar_maintenance_type: "oil-change",
      traccar_maintenance_name: "Oil change",
      interval_km: 15000,
      interval_days: 365,
      interval_hours: null,
      last_service_odometer_km: "185200.0",
      last_service_engine_hours: null,
      last_service_date: "2026-06-15",
      status: "due_soon",
      sync_error: false,
      created_at: "2026-01-10T00:00:00.000Z",
    },
    {
      id: 2,
      vehicle_id: 1,
      service_type_id: 2,
      service_type_name: "Tire rotation",
      traccar_maintenance_id: 1002,
      traccar_maintenance_type: "tire-rotation",
      traccar_maintenance_name: "Tire rotation",
      interval_km: 10000,
      interval_days: null,
      interval_hours: null,
      last_service_odometer_km: "178000.0",
      last_service_engine_hours: null,
      last_service_date: "2026-04-10",
      status: "overdue",
      sync_error: false,
      created_at: "2026-01-10T00:00:00.000Z",
    },
    {
      id: 3,
      vehicle_id: 2,
      service_type_id: 1,
      service_type_name: "Oil change",
      traccar_maintenance_id: 1003,
      traccar_maintenance_type: "oil-change",
      traccar_maintenance_name: "Oil change",
      interval_km: 15000,
      interval_days: 365,
      interval_hours: null,
      last_service_odometer_km: "96000.0",
      last_service_engine_hours: null,
      last_service_date: "2026-05-20",
      status: "ok",
      sync_error: false,
      created_at: "2026-01-10T00:00:00.000Z",
    },
    {
      id: 4,
      vehicle_id: 3,
      service_type_id: 3,
      service_type_name: "Annual inspection",
      traccar_maintenance_id: 1004,
      traccar_maintenance_type: "inspection",
      traccar_maintenance_name: "Annual inspection",
      interval_km: null,
      interval_days: 365,
      interval_hours: null,
      last_service_odometer_km: "138500.0",
      last_service_engine_hours: null,
      last_service_date: "2026-03-10",
      status: "overdue",
      sync_error: false,
      created_at: "2026-01-10T00:00:00.000Z",
    },
    {
      id: 5,
      vehicle_id: 4,
      service_type_id: 5,
      service_type_name: "Engine service",
      traccar_maintenance_id: 1005,
      traccar_maintenance_type: "engine-service",
      traccar_maintenance_name: "Engine service",
      interval_km: 30000,
      interval_days: 730,
      interval_hours: null,
      last_service_odometer_km: "310500.0",
      last_service_engine_hours: null,
      last_service_date: "2026-07-05",
      status: "ok",
      sync_error: false,
      created_at: "2026-01-10T00:00:00.000Z",
    },
  ];

  return {
    serviceTypes,
    vehicles,
    unregisteredDevices,
    records,
    parts,
    movements,
    reminders,
    nextIds: {
      vehicle: 5,
      record: 9,
      part: 7,
      movement: 14,
      reminder: 6,
      serviceType: 6,
      recordChange: 1,
    },
  };
}
